[Settings]
Enabled=true
Logging=true
Notification=false

; Gameplay
UseSellCooldown=false
SellCooldownMinutes=48
VehicleSellPercent=60
UpgradePercent=8
UseDamagePenalty=true
AllowCharacterVehicles=false
